services:
  - type: web
    name: finora
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeployTrigger: checksPass
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_FORWARDEDHEADERS_ENABLED
        value: "true"
      - key: ConnectionStrings__DefaultConnection
        sync: false
