import { CurrencyPipe, DatePipe, DecimalPipe } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, inject, OnInit, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';

interface FinancialProduct { id:string; productType:number; name:string; institution:string; lastFourDigits:string|null; currentBalance:number; creditLimit:number|null; originalPrincipal:number|null; interestRate:number|null; monthlyPayment:number|null; paymentDay:number|null; startDate:string|null; endDate:string|null; expiryDate:string|null; currencyCode:string; isActive:boolean; notes:string|null; }

@Component({
  standalone:true,
  imports:[CurrencyPipe,DatePipe,DecimalPipe,ReactiveFormsModule,MatButtonModule,MatCardModule,MatFormFieldModule,MatIconModule,MatInputModule,MatSlideToggleModule],
  template:`
    <header><p class="eyebrow">{{eyebrow}}</p><h1>{{title}}</h1><p>{{description}}</p></header>
    <div class="layout"><mat-card class="form-card"><h2>{{editingId()?'Edit '+singular:'Add '+singular}}</h2><form [formGroup]="form" (ngSubmit)="save()"><div class="fields">
      <mat-form-field><mat-label>{{singular}} name</mat-label><input matInput formControlName="name" [placeholder]="namePlaceholder"></mat-form-field><mat-form-field><mat-label>Bank or institution</mat-label><input matInput formControlName="institution"></mat-form-field>
      @if(type===1||type===2){<mat-form-field><mat-label>Last four digits (optional)</mat-label><input matInput inputmode="numeric" maxlength="4" formControlName="lastFourDigits" placeholder="1234"></mat-form-field>}
      <mat-form-field><mat-label>{{type===1?'Outstanding balance':type===3?'Current value':'Current balance'}}</mat-label><input matInput type="number" min="0" step="0.01" formControlName="currentBalance"><span matTextSuffix>EUR</span></mat-form-field>
      @if(type===0){<mat-form-field><mat-label>Original principal</mat-label><input matInput type="number" min="0.01" formControlName="originalPrincipal"><span matTextSuffix>EUR</span></mat-form-field><mat-form-field><mat-label>Interest rate</mat-label><input matInput type="number" min="0" step="0.001" formControlName="interestRate"><span matTextSuffix>%</span></mat-form-field><mat-form-field><mat-label>Monthly payment</mat-label><input matInput type="number" min="0.01" formControlName="monthlyPayment"><span matTextSuffix>EUR</span></mat-form-field><mat-form-field><mat-label>Payment day</mat-label><input matInput type="number" min="1" max="31" formControlName="paymentDay"></mat-form-field><mat-form-field><mat-label>Start date</mat-label><input matInput type="date" formControlName="startDate"></mat-form-field><mat-form-field><mat-label>End date</mat-label><input matInput type="date" formControlName="endDate"></mat-form-field>}
      @if(type===1){<mat-form-field><mat-label>Credit limit</mat-label><input matInput type="number" min="0.01" formControlName="creditLimit"><span matTextSuffix>EUR</span></mat-form-field><mat-form-field><mat-label>Payment day</mat-label><input matInput type="number" min="1" max="31" formControlName="paymentDay"></mat-form-field>}
      @if(type===1||type===2){<mat-form-field><mat-label>Expiry date (optional)</mat-label><input matInput type="date" formControlName="expiryDate"></mat-form-field>}
      @if(type===3){<mat-form-field><mat-label>Total invested</mat-label><input matInput type="number" min="0" step="0.01" formControlName="originalPrincipal"><span matTextSuffix>EUR</span></mat-form-field><mat-form-field><mat-label>Investment date</mat-label><input matInput type="date" formControlName="startDate"></mat-form-field>}
      <mat-form-field class="wide"><mat-label>Notes (optional)</mat-label><textarea matInput rows="3" maxlength="1000" formControlName="notes"></textarea></mat-form-field><mat-slide-toggle formControlName="isActive">Active</mat-slide-toggle>
    </div>@if(validationError()){<p class="error">{{validationError()}}</p>}<div class="actions"><button mat-flat-button type="submit" [disabled]="form.invalid||saving()||!!validationError()">{{saving()?'Saving…':editingId()?'Save changes':'Add '+singular}}</button>@if(editingId()){<button mat-button type="button" (click)="cancelEdit()">Cancel</button>}</div></form></mat-card>
    <section class="products" aria-live="polite">@if(loading()){<mat-card class="empty">Loading {{title.toLowerCase()}}…</mat-card>}@else if(!products().length){<mat-card class="empty"><mat-icon>{{icon}}</mat-icon><h2>No {{title.toLowerCase()}} yet</h2><p>Add your first {{singular}}.</p></mat-card>}@for(item of products();track item.id){<mat-card class="product"><div class="product-head"><span class="product-icon"><mat-icon>{{icon}}</mat-icon></span><div><h2>{{item.name}}</h2><p>{{item.institution}}@if(item.lastFourDigits){ · •••• {{item.lastFourDigits}}}</p></div><div><button mat-icon-button (click)="edit(item)" [attr.aria-label]="'Edit '+item.name"><mat-icon>edit</mat-icon></button><button mat-icon-button (click)="remove(item)" [attr.aria-label]="'Delete '+item.name"><mat-icon>delete_outline</mat-icon></button></div></div><strong>{{item.currentBalance|currency:item.currencyCode}}</strong><span class="caption">{{type===1?'outstanding':type===0?'remaining balance':type===3?'current value':'available balance'}}</span><dl>@if(item.creditLimit){<div><dt>Credit limit</dt><dd>{{item.creditLimit|currency:item.currencyCode}}</dd></div>}@if(item.monthlyPayment){<div><dt>Monthly payment</dt><dd>{{item.monthlyPayment|currency:item.currencyCode}}</dd></div>}@if(item.interestRate!==null){<div><dt>Interest</dt><dd>{{item.interestRate|number:'1.2-4'}}%</dd></div>}@if(item.paymentDay){<div><dt>Payment day</dt><dd>Day {{item.paymentDay}}</dd></div>}@if(item.expiryDate){<div><dt>Expires</dt><dd>{{item.expiryDate|date:'MMM y'}}</dd></div>}@if(type===3&&item.originalPrincipal!==null){<div><dt>Total invested</dt><dd>{{item.originalPrincipal|currency:item.currencyCode}}</dd></div><div><dt>Gain / loss</dt><dd>{{item.currentBalance-item.originalPrincipal|currency:item.currencyCode}}</dd></div>}@if(type===3&&item.startDate){<div><dt>Invested since</dt><dd>{{item.startDate|date:'mediumDate'}}</dd></div>}</dl><span class="status" [class.inactive]="!item.isActive">{{item.isActive?'Active':'Inactive'}}</span>@if(item.notes){<p class="notes">{{item.notes}}</p>}</mat-card>}</section></div>`,
  styles:[`header h1{font-size:clamp(1.8rem,4vw,2.6rem);margin:.15rem 0}.eyebrow{letter-spacing:.15em;color:#397454;font-weight:700}.layout{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(330px,.95fr);gap:1.25rem;margin-top:2rem;align-items:start}mat-card{padding:1.3rem}.fields{display:grid;grid-template-columns:1fr 1fr;gap:0 1rem}.wide{grid-column:1/-1}.actions{display:flex;gap:.5rem;margin-top:1rem}.actions button:first-child{flex:1}.products{display:grid;gap:1rem}.empty{min-height:220px;display:grid;place-content:center;text-align:center;color:#68766f}.empty>mat-icon{margin:auto;font-size:42px;width:42px;height:42px;color:#397454}.product-head{display:grid;grid-template-columns:auto 1fr auto;gap:.8rem}.product-icon{display:grid;place-items:center;width:42px;height:42px;border-radius:13px;background:#e3f1e6;color:#285844}.product h2{margin:0;font-size:1.1rem}.product p,.caption,dt{color:#68766f}.product>strong{display:block;font-size:1.8rem;margin-top:1.2rem}.caption{font-size:.82rem}dl{display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:1.2rem 0}dt{font-size:.75rem}dd{margin:.2rem 0 0;font-weight:600}.status{display:inline-block;padding:.3rem .65rem;border-radius:999px;background:#e3f1e6;color:#285844;font-size:.78rem;font-weight:700}.status.inactive{background:#eee;color:#666}.notes{padding-top:.8rem;border-top:1px solid #e3e9e5;white-space:pre-wrap}.error{color:#b3261e;font-size:.85rem}@media(max-width:1000px){.layout{grid-template-columns:1fr}}@media(max-width:600px){.fields,dl{grid-template-columns:1fr}.wide{grid-column:auto}.product-head{grid-template-columns:auto 1fr}.product-head>div:last-child{grid-column:2}}`]
})
export class FinancialProductsComponent implements OnInit {
  private readonly http=inject(HttpClient); private readonly route=inject(ActivatedRoute); readonly type=Number(this.route.snapshot.data['type']); readonly products=signal<FinancialProduct[]>([]); readonly loading=signal(true); readonly saving=signal(false); readonly editingId=signal<string|null>(null);
  readonly configs=[{title:'Loans',singular:'loan',eyebrow:'PERSONAL FINANCE',description:'Track personal, vehicle, and other loans with their remaining balance and monthly payment.',icon:'request_quote',route:'loans',placeholder:'Car loan'},{title:'Credit cards',singular:'credit card',eyebrow:'REVOLVING CREDIT',description:'Monitor card balances, limits, payment dates, and expiry details.',icon:'credit_card',route:'credit-cards',placeholder:'Everyday rewards'},{title:'Debit cards',singular:'debit card',eyebrow:'DAILY BANKING',description:'Keep debit card balances, institutions, and expiry details organised.',icon:'payment',route:'debit-cards',placeholder:'Daily debit'},{title:'Investments',singular:'investment',eyebrow:'WEALTH BUILDING',description:'Track invested capital, current value, performance, institution, and status.',icon:'monitoring',route:'investments',placeholder:'Index fund'}]; readonly config=this.configs[this.type]; readonly title=this.config.title; readonly singular=this.config.singular; readonly eyebrow=this.config.eyebrow; readonly description=this.config.description; readonly icon=this.config.icon; readonly namePlaceholder=this.config.placeholder; readonly api=`/api/${this.config.route}`;
  readonly form=new FormGroup({name:new FormControl('',{nonNullable:true,validators:[Validators.required]}),institution:new FormControl('',{nonNullable:true,validators:[Validators.required]}),lastFourDigits:new FormControl('',{nonNullable:true,validators:[Validators.pattern(/^$|^\d{4}$/)]}),currentBalance:new FormControl<number|null>(null,[Validators.required,Validators.min(0)]),creditLimit:new FormControl<number|null>(null),originalPrincipal:new FormControl<number|null>(null),interestRate:new FormControl<number|null>(null),monthlyPayment:new FormControl<number|null>(null),paymentDay:new FormControl<number|null>(null),startDate:new FormControl('',{nonNullable:true}),endDate:new FormControl('',{nonNullable:true}),expiryDate:new FormControl('',{nonNullable:true}),currencyCode:new FormControl('EUR',{nonNullable:true}),isActive:new FormControl(true,{nonNullable:true}),notes:new FormControl('',{nonNullable:true,validators:[Validators.maxLength(1000)]})});
  ngOnInit(){this.load();} load(){this.http.get<FinancialProduct[]>(this.api).subscribe({next:x=>{this.products.set(x);this.loading.set(false)},error:()=>this.loading.set(false)});}
  validationError(){const v=this.form.getRawValue();if(this.type===0){if(!v.originalPrincipal||!v.monthlyPayment||v.interestRate===null||!v.paymentDay||!v.startDate||!v.endDate)return 'Complete all loan details.';if(v.endDate<=v.startDate)return 'End date must be after start date.';if((v.currentBalance??0)>v.originalPrincipal)return 'Balance cannot exceed the original principal.';}if(this.type===1){if(!v.creditLimit||!v.paymentDay)return 'Credit limit and payment day are required.';if((v.currentBalance??0)>v.creditLimit)return 'Balance cannot exceed the credit limit.';}if(this.type===3&&(v.originalPrincipal===null||!v.startDate))return 'Invested amount and investment date are required.';return null;}
  payload(){const v=this.form.getRawValue();return{...v,lastFourDigits:v.lastFourDigits||null,startDate:v.startDate||null,endDate:v.endDate||null,expiryDate:v.expiryDate||null,notes:v.notes.trim()||null};}
  save(){if(this.form.invalid||this.validationError())return;this.saving.set(true);const id=this.editingId();const request=id?this.http.put<FinancialProduct>(`${this.api}/${id}`,this.payload()):this.http.post<FinancialProduct>(this.api,this.payload());request.subscribe({next:x=>{this.products.update(items=>(id?items.map(item=>item.id===id?x:item):[...items,x]).sort((a,b)=>a.name.localeCompare(b.name)));this.cancelEdit();this.saving.set(false)},error:()=>this.saving.set(false)});}
  edit(x:FinancialProduct){this.editingId.set(x.id);this.form.setValue({name:x.name,institution:x.institution,lastFourDigits:x.lastFourDigits??'',currentBalance:x.currentBalance,creditLimit:x.creditLimit,originalPrincipal:x.originalPrincipal,interestRate:x.interestRate,monthlyPayment:x.monthlyPayment,paymentDay:x.paymentDay,startDate:x.startDate??'',endDate:x.endDate??'',expiryDate:x.expiryDate??'',currencyCode:x.currencyCode,isActive:x.isActive,notes:x.notes??''});window.scrollTo({top:0,behavior:'smooth'});} cancelEdit(){this.editingId.set(null);this.form.reset({currencyCode:'EUR',isActive:true,lastFourDigits:'',startDate:'',endDate:'',expiryDate:'',notes:''});}
  remove(x:FinancialProduct){if(!confirm(`Delete ${x.name}?`))return;this.http.delete(`${this.api}/${x.id}`).subscribe(()=>this.products.update(items=>items.filter(item=>item.id!==x.id)));}
}
