import { HttpClient } from '@angular/common/http';
import { Component, inject, OnInit, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';

interface Category { id:string; name:string; categoryType:number; icon:string; color:string; isDefault:boolean; }

@Component({
  standalone:true,
  imports:[ReactiveFormsModule,MatButtonModule,MatCardModule,MatFormFieldModule,MatIconModule,MatInputModule,MatSelectModule],
  template:`
    <header><p class="eyebrow">ORGANISE YOUR MONEY</p><h1>Categories</h1><p>Create colour-coded income and expense categories for transactions and budgets.</p></header>
    <div class="layout"><mat-card class="form-card"><h2>{{editingId()?'Edit category':'Create a category'}}</h2><form [formGroup]="form" (ngSubmit)="save()"><div class="fields">
      <mat-form-field class="wide"><mat-label>Category name</mat-label><input matInput formControlName="name" placeholder="Dining out"></mat-form-field>
      <mat-form-field><mat-label>Type</mat-label><mat-select formControlName="categoryType"><mat-option [value]="1">Expense</mat-option><mat-option [value]="0">Income</mat-option></mat-select></mat-form-field>
      <mat-form-field><mat-label>Icon</mat-label><mat-select formControlName="icon">@for(item of icons;track item.value){<mat-option [value]="item.value"><mat-icon>{{item.value}}</mat-icon>{{item.label}}</mat-option>}</mat-select></mat-form-field>
      <label class="color-field"><span>Color</span><span class="color-control"><input type="color" formControlName="color" aria-label="Category color"><code>{{form.controls.color.value.toUpperCase()}}</code></span></label>
      <div class="preview"><span [style.background]="form.controls.color.value"><mat-icon>{{form.controls.icon.value}}</mat-icon></span><div><strong>{{form.controls.name.value||'Category preview'}}</strong><small>{{form.controls.categoryType.value===1?'Expense':'Income'}}</small></div></div>
    </div>@if(error()){<p class="error">{{error()}}</p>}<div class="actions"><button mat-flat-button type="submit" [disabled]="form.invalid||saving()">{{saving()?'Saving…':editingId()?'Save changes':'Create category'}}</button>@if(editingId()){<button mat-button type="button" (click)="cancelEdit()">Cancel</button>}</div></form></mat-card>
    <section class="category-list" aria-live="polite">@if(loading()){<mat-card class="empty">Loading categories…</mat-card>}@else if(!categories().length){<mat-card class="empty"><mat-icon>category</mat-icon><h2>No categories yet</h2><p>Create your first income or expense category.</p></mat-card>}@for(group of groups;track group.type){<div class="group"><h2>{{group.label}} <span>{{categoriesOfType(group.type).length}}</span></h2>@for(category of categoriesOfType(group.type);track category.id){<mat-card class="category-card"><span class="category-icon" [style.background]="category.color"><mat-icon>{{category.icon}}</mat-icon></span><div><h3>{{category.name}}</h3><p><span class="color-dot" [style.background]="category.color"></span>{{category.color}}@if(category.isDefault){ · Default}</p></div><div class="card-actions"><button mat-icon-button (click)="edit(category)" [attr.aria-label]="'Edit '+category.name"><mat-icon>edit</mat-icon></button>@if(!category.isDefault){<button mat-icon-button (click)="remove(category)" [attr.aria-label]="'Delete '+category.name"><mat-icon>delete_outline</mat-icon></button>}</div></mat-card>}</div>}</section></div>`,
  styles:[`header h1{font-size:clamp(1.8rem,4vw,2.6rem);margin:.15rem 0}.eyebrow{letter-spacing:.15em;color:#397454;font-weight:700}.layout{display:grid;grid-template-columns:minmax(320px,.8fr) minmax(0,1.2fr);gap:1.25rem;margin-top:2rem;align-items:start}mat-card{padding:1.3rem}.form-card{position:sticky;top:84px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:0 1rem}.wide{grid-column:1/-1}.color-field{display:grid;gap:.45rem;color:#3f4944;font-size:.85rem}.color-control{display:flex;align-items:center;gap:.7rem;height:56px;padding:0 .85rem;border:1px solid #747d78;border-radius:4px}.color-control input{width:42px;height:34px;padding:0;border:0;background:none;cursor:pointer}.color-control code{color:#53675c}.preview{display:flex;align-items:center;gap:.75rem}.preview>span,.category-icon{display:grid;place-items:center;width:46px;height:46px;border-radius:14px;color:#fff}.preview div{display:grid}.preview small{color:#68766f}.actions{display:flex;gap:.5rem;margin-top:1.2rem}.actions button:first-child{flex:1}.category-list{display:grid;gap:1.5rem}.group{display:grid;gap:.7rem}.group>h2{display:flex;align-items:center;gap:.5rem;margin:0;font-size:1.05rem}.group>h2 span{padding:.15rem .5rem;border-radius:999px;background:#e3ebe5;color:#53675c;font-size:.75rem}.category-card{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:.85rem}.category-card h3{margin:0;font-size:1rem}.category-card p{display:flex;align-items:center;margin:.2rem 0 0;color:#68766f;font-size:.78rem}.color-dot{width:9px;height:9px;margin-right:.35rem;border-radius:50%}.card-actions{display:flex}.empty{min-height:220px;display:grid;place-content:center;text-align:center;color:#68766f}.empty>mat-icon{margin:auto;font-size:42px;width:42px;height:42px;color:#397454}.error{color:#b3261e;font-size:.85rem}@media(max-width:900px){.layout{grid-template-columns:1fr}.form-card{position:static}}@media(max-width:520px){.fields{grid-template-columns:1fr}.wide{grid-column:auto}.category-card{grid-template-columns:auto 1fr}.card-actions{grid-column:2}}`]
})
export class CategoriesComponent implements OnInit {
  private readonly http=inject(HttpClient); readonly categories=signal<Category[]>([]); readonly loading=signal(true); readonly saving=signal(false); readonly editingId=signal<string|null>(null); readonly error=signal('');
  readonly groups=[{type:1,label:'Expense categories'},{type:0,label:'Income categories'}]; readonly icons=[{value:'category',label:'General'},{value:'home',label:'Home'},{value:'shopping_cart',label:'Groceries'},{value:'restaurant',label:'Dining'},{value:'directions_car',label:'Transport'},{value:'bolt',label:'Utilities'},{value:'medical_services',label:'Health'},{value:'sports_esports',label:'Entertainment'},{value:'shopping_bag',label:'Shopping'},{value:'subscriptions',label:'Subscriptions'},{value:'school',label:'Education'},{value:'pets',label:'Pets'},{value:'flight',label:'Travel'},{value:'payments',label:'Salary'},{value:'work',label:'Work'},{value:'monitoring',label:'Investments'},{value:'redeem',label:'Gifts'},{value:'savings',label:'Savings'}];
  readonly form=new FormGroup({name:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(80)]}),categoryType:new FormControl(1,{nonNullable:true,validators:[Validators.required]}),icon:new FormControl('category',{nonNullable:true,validators:[Validators.required]}),color:new FormControl('#397454',{nonNullable:true,validators:[Validators.required,Validators.pattern(/^#[0-9a-fA-F]{6}$/)]})});
  ngOnInit(){this.load();} load(){this.http.get<Category[]>('/api/categories').subscribe({next:x=>{this.categories.set(x);this.loading.set(false)},error:()=>this.loading.set(false)});} categoriesOfType(type:number){return this.categories().filter(x=>x.categoryType===type);}
  save(){if(this.form.invalid)return;this.saving.set(true);this.error.set('');const id=this.editingId();const request=id?this.http.put<Category>(`/api/categories/${id}`,this.form.getRawValue()):this.http.post<Category>('/api/categories',this.form.getRawValue());request.subscribe({next:x=>{this.categories.update(items=>(id?items.map(item=>item.id===id?x:item):[...items,x]).sort((a,b)=>a.name.localeCompare(b.name)));this.cancelEdit();this.saving.set(false)},error:response=>{this.error.set(response.error?.detail??response.error?.title??'Could not save this category.');this.saving.set(false)}});}
  edit(x:Category){this.editingId.set(x.id);this.error.set('');this.form.setValue({name:x.name,categoryType:x.categoryType,icon:x.icon,color:x.color});window.scrollTo({top:0,behavior:'smooth'});} cancelEdit(){this.editingId.set(null);this.error.set('');this.form.reset({name:'',categoryType:1,icon:'category',color:'#397454'});}
  remove(x:Category){if(!confirm(`Delete ${x.name}? Transactions using it will become uncategorised.`))return;this.http.delete(`/api/categories/${x.id}`).subscribe({next:()=>this.categories.update(items=>items.filter(item=>item.id!==x.id)),error:()=>this.error.set('This category is still used by a budget and cannot be deleted.')});}
}
