using Finora.Api.Data;
using Finora.Api.Features;
using Microsoft.EntityFrameworkCore;

namespace Finora.Api.Tests;

public sealed class FinanceServiceTests
{
    private static FinoraDbContext Database() => new(new DbContextOptionsBuilder<FinoraDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);
    [Fact] public void Registration_validation_requires_a_display_name() { var request=new RegisterRequest("person@example.com","long-password",""); Assert.True(string.IsNullOrWhiteSpace(request.DisplayName)); }
    [Fact] public void Api_finance_routes_require_authentication() { var method=typeof(Endpoints).GetMethod(nameof(Endpoints.MapFinoraEndpoints)); Assert.NotNull(method); }
    [Fact] public async Task Users_cannot_access_another_users_accounts() { await using var db=Database(); var owner=Guid.NewGuid(); db.Accounts.Add(new(){UserId=owner,Name="Private"}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Accounts(Guid.NewGuid()); Assert.Empty(result); }
    [Fact] public async Task Creating_an_account_sets_the_owner() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreateAccount(user,new("Daily",AccountType.CurrentAccount,"eur",100)); Assert.Equal(user,result.UserId); Assert.Equal("EUR",result.CurrencyCode); }
    [Fact] public async Task Creating_an_expense_transaction_is_user_scoped() { await using var db=Database(); var user=Guid.NewGuid(); var account=new Account{UserId=user,Name="Daily"}; db.Add(account); await db.SaveChangesAsync(); var result=await new FinanceService(db).CreateTransaction(user,new(account.Id,null,TransactionType.Expense,20,"Food",DateOnly.FromDateTime(DateTime.UtcNow),null)); Assert.Equal(TransactionType.Expense,result.TransactionType); Assert.Equal(20,result.Amount); }
    [Fact] public async Task Dashboard_calculates_income_and_expenses() { await using var db=Database(); var user=Guid.NewGuid(); var account=new Account{UserId=user,Name="Daily",InitialBalance=100}; db.Add(account); db.Transactions.AddRange(new(){UserId=user,AccountId=account.Id,TransactionType=TransactionType.Income,Amount=50,Description="Pay",TransactionDate=new(2026,8,1)},new(){UserId=user,AccountId=account.Id,TransactionType=TransactionType.Expense,Amount=25,Description="Food",TransactionDate=new(2026,8,2)}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Dashboard(user,8,2026); Assert.Contains("monthlyIncome = 50",result.ToString()); Assert.Contains("monthlyExpenses = 25",result.ToString()); }
    [Fact] public async Task Creating_a_mortgage_sets_owner_and_normalizes_currency() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreateMortgage(user,new("Home","Bank","Lisbon",250000,220000,3.25m,MortgageRateType.Variable,950,"eur",new(2024,1,1),new(2054,1,1),5)); Assert.Equal(user,result.UserId); Assert.Equal("EUR",result.CurrencyCode); Assert.Equal(220000,result.OutstandingBalance); }
    [Fact] public async Task Mortgages_are_user_scoped() { await using var db=Database(); var owner=Guid.NewGuid(); db.Mortgages.Add(new(){UserId=owner,Name="Private home",Lender="Bank",OriginalPrincipal=100000,OutstandingBalance=90000,MonthlyPayment=500,StartDate=new(2020,1,1),EndDate=new(2050,1,1),PaymentDay=1}); await db.SaveChangesAsync(); Assert.Empty(await new FinanceService(db).Mortgages(Guid.NewGuid())); }
    [Fact] public async Task Mortgage_rejects_balance_above_original_principal() { await using var db=Database(); var service=new FinanceService(db); await Assert.ThrowsAsync<ArgumentException>(()=>service.CreateMortgage(Guid.NewGuid(),new("Home","Bank",null,100000,110000,3,MortgageRateType.Fixed,500,"EUR",new(2024,1,1),new(2054,1,1),1))); }
    [Fact] public async Task Updating_a_mortgage_changes_only_the_owners_record() { await using var db=Database(); var owner=Guid.NewGuid(); var mortgage=new Mortgage{UserId=owner,Name="Home",Lender="Bank",OriginalPrincipal=100000,OutstandingBalance=90000,InterestRate=3,MonthlyPayment=500,StartDate=new(2020,1,1),EndDate=new(2050,1,1),PaymentDay=1}; db.Add(mortgage); await db.SaveChangesAsync(); var service=new FinanceService(db); var updated=await service.UpdateMortgage(owner,mortgage.Id,new("Home","New bank",null,100000,80000,2.5m,MortgageRateType.Fixed,475,"EUR",new(2020,1,1),new(2050,1,1),2)); Assert.Equal(80000,updated.OutstandingBalance); Assert.Equal("New bank",updated.Lender); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.UpdateMortgage(Guid.NewGuid(),mortgage.Id,new("Home","Other",null,100000,70000,2,MortgageRateType.Fixed,450,"EUR",new(2020,1,1),new(2050,1,1),2))); }
    [Fact] public async Task Dashboard_includes_active_mortgage_payment_as_an_expense() { await using var db=Database(); var user=Guid.NewGuid(); db.Mortgages.Add(new(){UserId=user,Name="Home",Lender="Bank",OriginalPrincipal=100000,OutstandingBalance=90000,MonthlyPayment=500,StartDate=new(2020,1,1),EndDate=new(2050,1,1),PaymentDay=1}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Dashboard(user,8,2026); Assert.Contains("monthlyExpenses = 500",result.ToString()); Assert.Contains("mortgageExpenses = 500",result.ToString()); }
}
