using Finora.Api.Data;
using Finora.Api.Features;
using Microsoft.EntityFrameworkCore;

namespace Finora.Api.Tests;

public sealed class FinanceServiceTests
{
    private static FinoraDbContext Database() => new(new DbContextOptionsBuilder<FinoraDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);
    [Fact] public void Registration_validation_requires_a_display_name() { var request=new RegisterRequest("person@example.com","long-password",""); Assert.True(string.IsNullOrWhiteSpace(request.DisplayName)); }
    [Fact] public void Api_finance_routes_require_authentication() { var method=typeof(Endpoints).GetMethod(nameof(Endpoints.MapFinoraEndpoints)); Assert.NotNull(method); }
    [Fact] public async Task Users_cannot_access_another_users_accounts() { await using var db=Database(); var owner=Guid.NewGuid(); db.Accounts.Add(new(){UserId=owner,Name="Private"}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Accounts(Guid.NewGuid()); Assert.Empty(result); }
    [Fact] public async Task Creating_an_account_sets_the_owner() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreateAccount(user,new("Daily",AccountType.CurrentAccount,"eur",100)); Assert.Equal(user,result.UserId); Assert.Equal("EUR",result.CurrencyCode); }
    [Fact] public async Task Creating_an_expense_transaction_is_user_scoped() { await using var db=Database(); var user=Guid.NewGuid(); var account=new Account{UserId=user,Name="Daily"}; db.Add(account); await db.SaveChangesAsync(); var result=await new FinanceService(db).CreateTransaction(user,new(account.Id,null,TransactionType.Expense,20,"Food",DateOnly.FromDateTime(DateTime.UtcNow),null)); Assert.Equal(TransactionType.Expense,result.TransactionType); Assert.Equal(20,result.Amount); }
    [Fact] public async Task Dashboard_calculates_income_and_expenses() { await using var db=Database(); var user=Guid.NewGuid(); var account=new Account{UserId=user,Name="Daily",InitialBalance=100}; db.Add(account); db.Transactions.AddRange(new(){UserId=user,AccountId=account.Id,TransactionType=TransactionType.Income,Amount=50,Description="Pay",TransactionDate=new(2026,8,1)},new(){UserId=user,AccountId=account.Id,TransactionType=TransactionType.Expense,Amount=25,Description="Food",TransactionDate=new(2026,8,2)}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Dashboard(user,8,2026); Assert.Contains("monthlyIncome = 50",result.ToString()); Assert.Contains("monthlyExpenses = 25",result.ToString()); }
    [Fact] public async Task Creating_a_mortgage_sets_owner_and_normalizes_currency() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreateMortgage(user,new("Home","Bank","Lisbon",250000,220000,3.25m,MortgageRateType.Variable,950,"eur",new(2024,1,1),new(2054,1,1),5)); Assert.Equal(user,result.UserId); Assert.Equal("EUR",result.CurrencyCode); Assert.Equal(220000,result.OutstandingBalance); }
    [Fact] public async Task Mortgages_are_user_scoped() { await using var db=Database(); var owner=Guid.NewGuid(); db.Mortgages.Add(new(){UserId=owner,Name="Private home",Lender="Bank",OriginalPrincipal=100000,OutstandingBalance=90000,MonthlyPayment=500,StartDate=new(2020,1,1),EndDate=new(2050,1,1),PaymentDay=1}); await db.SaveChangesAsync(); Assert.Empty(await new FinanceService(db).Mortgages(Guid.NewGuid())); }
    [Fact] public async Task Mortgage_rejects_balance_above_original_principal() { await using var db=Database(); var service=new FinanceService(db); await Assert.ThrowsAsync<ArgumentException>(()=>service.CreateMortgage(Guid.NewGuid(),new("Home","Bank",null,100000,110000,3,MortgageRateType.Fixed,500,"EUR",new(2024,1,1),new(2054,1,1),1))); }
    [Fact] public async Task Updating_a_mortgage_changes_only_the_owners_record() { await using var db=Database(); var owner=Guid.NewGuid(); var mortgage=new Mortgage{UserId=owner,Name="Home",Lender="Bank",OriginalPrincipal=100000,OutstandingBalance=90000,InterestRate=3,MonthlyPayment=500,StartDate=new(2020,1,1),EndDate=new(2050,1,1),PaymentDay=1}; db.Add(mortgage); await db.SaveChangesAsync(); var service=new FinanceService(db); var updated=await service.UpdateMortgage(owner,mortgage.Id,new("Home","New bank",null,100000,80000,2.5m,MortgageRateType.Fixed,475,"EUR",new(2020,1,1),new(2050,1,1),2)); Assert.Equal(80000,updated.OutstandingBalance); Assert.Equal("New bank",updated.Lender); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.UpdateMortgage(Guid.NewGuid(),mortgage.Id,new("Home","Other",null,100000,70000,2,MortgageRateType.Fixed,450,"EUR",new(2020,1,1),new(2050,1,1),2))); }
    [Fact] public async Task Dashboard_includes_active_mortgage_payment_as_an_expense() { await using var db=Database(); var user=Guid.NewGuid(); db.Mortgages.Add(new(){UserId=user,Name="Home",Lender="Bank",OriginalPrincipal=100000,OutstandingBalance=90000,MonthlyPayment=500,StartDate=new(2020,1,1),EndDate=new(2050,1,1),PaymentDay=1}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Dashboard(user,8,2026); Assert.Contains("monthlyExpenses = 500",result.ToString()); Assert.Contains("mortgageExpenses = 500",result.ToString()); }
    [Fact] public async Task Creating_a_household_bill_sets_owner_and_normalizes_currency() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreateHouseholdBill(user,new("Home internet","Fiber Co",HouseholdBillType.Internet,39.99m,"eur",12,new(2026,1,1),null,true)); Assert.Equal(user,result.UserId); Assert.Equal("EUR",result.CurrencyCode); Assert.Equal(HouseholdBillType.Internet,result.BillType); }
    [Fact] public async Task Household_bills_are_user_scoped() { await using var db=Database(); var owner=Guid.NewGuid(); db.HouseholdBills.Add(new(){UserId=owner,Name="Water",Provider="Utility",BillType=HouseholdBillType.Water,Amount=25,BillingDay=10,StartDate=new(2026,1,1)}); await db.SaveChangesAsync(); Assert.Empty(await new FinanceService(db).HouseholdBills(Guid.NewGuid())); }
    [Fact] public async Task Household_bill_rejects_an_invalid_billing_day() { await using var db=Database(); var service=new FinanceService(db); await Assert.ThrowsAsync<ArgumentException>(()=>service.CreateHouseholdBill(Guid.NewGuid(),new("Gas","Provider",HouseholdBillType.Gas,30,"EUR",32,new(2026,1,1),null,true))); }
    [Fact] public async Task Updating_a_household_bill_enforces_ownership() { await using var db=Database(); var owner=Guid.NewGuid(); var bill=new HouseholdBill{UserId=owner,Name="Mobile",Provider="Carrier",BillType=HouseholdBillType.MobilePlan,Amount=20,BillingDay=1,StartDate=new(2026,1,1)}; db.Add(bill); await db.SaveChangesAsync(); var service=new FinanceService(db); var updated=await service.UpdateHouseholdBill(owner,bill.Id,new("Mobile family","Carrier",HouseholdBillType.MobilePlan,35,"EUR",5,new(2026,1,1),null,true)); Assert.Equal(35,updated.Amount); Assert.Equal(5,updated.BillingDay); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.UpdateHouseholdBill(Guid.NewGuid(),bill.Id,new("Other","Carrier",HouseholdBillType.MobilePlan,10,"EUR",1,new(2026,1,1),null,true))); }
    [Fact] public async Task Dashboard_includes_only_active_household_bills_for_the_month() { await using var db=Database(); var user=Guid.NewGuid(); db.HouseholdBills.AddRange(new(){UserId=user,Name="Electricity",Provider="Power",BillType=HouseholdBillType.Electricity,Amount=60,BillingDay=8,StartDate=new(2026,1,1),IsActive=true},new(){UserId=user,Name="Old internet",Provider="ISP",BillType=HouseholdBillType.Internet,Amount=40,BillingDay=1,StartDate=new(2025,1,1),EndDate=new(2026,7,31),IsActive=true},new(){UserId=user,Name="Paused gas",Provider="Gas",BillType=HouseholdBillType.Gas,Amount=30,BillingDay=2,StartDate=new(2026,1,1),IsActive=false}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Dashboard(user,8,2026); Assert.Contains("monthlyExpenses = 60",result.ToString()); Assert.Contains("householdBillExpenses = 60",result.ToString()); }
    [Fact] public async Task Creating_a_medical_expense_sets_owner_and_normalizes_values() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreateMedicalExpense(user,new("Prescription medicine","Local Pharmacy",MedicalExpenseType.Pharmacy,18.50m,"eur",new(2026,8,7),"  Monthly prescription  ",true)); Assert.Equal(user,result.UserId); Assert.Equal("EUR",result.CurrencyCode); Assert.Equal("Monthly prescription",result.Notes); Assert.True(result.IsReimbursable); }
    [Fact] public async Task Medical_expenses_are_user_scoped() { await using var db=Database(); var owner=Guid.NewGuid(); db.MedicalExpenses.Add(new(){UserId=owner,Description="Exam",Provider="Clinic",ExpenseType=MedicalExpenseType.Exam,Amount=75,ExpenseDate=new(2026,8,7)}); await db.SaveChangesAsync(); Assert.Empty(await new FinanceService(db).MedicalExpenses(Guid.NewGuid())); }
    [Fact] public async Task Medical_expense_rejects_a_non_positive_amount() { await using var db=Database(); await Assert.ThrowsAsync<ArgumentException>(()=>new FinanceService(db).CreateMedicalExpense(Guid.NewGuid(),new("Appointment","Clinic",MedicalExpenseType.Appointment,0,"EUR",new(2026,8,7),null,false))); }
    [Fact] public async Task Updating_a_medical_expense_enforces_ownership() { await using var db=Database(); var owner=Guid.NewGuid(); var expense=new MedicalExpense{UserId=owner,Description="Exam",Provider="Clinic",ExpenseType=MedicalExpenseType.Exam,Amount=75,ExpenseDate=new(2026,8,7)}; db.Add(expense); await db.SaveChangesAsync(); var service=new FinanceService(db); var updated=await service.UpdateMedicalExpense(owner,expense.Id,new("Blood exam","Lab",MedicalExpenseType.Exam,45,"EUR",new(2026,8,8),null,true)); Assert.Equal(45,updated.Amount); Assert.Equal("Lab",updated.Provider); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.UpdateMedicalExpense(Guid.NewGuid(),expense.Id,new("Other","Clinic",MedicalExpenseType.Other,10,"EUR",new(2026,8,8),null,false))); }
    [Fact] public async Task Dashboard_includes_only_medical_expenses_from_the_selected_month() { await using var db=Database(); var user=Guid.NewGuid(); db.MedicalExpenses.AddRange(new(){UserId=user,Description="Appointment",Provider="Clinic",ExpenseType=MedicalExpenseType.Appointment,Amount=50,ExpenseDate=new(2026,8,2)},new(){UserId=user,Description="Old exam",Provider="Lab",ExpenseType=MedicalExpenseType.Exam,Amount=80,ExpenseDate=new(2026,7,30)}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Dashboard(user,8,2026); Assert.Contains("monthlyExpenses = 50",result.ToString()); Assert.Contains("medicalExpenses = 50",result.ToString()); }
    [Fact] public async Task Creating_a_supermarket_expense_sets_owner_and_normalizes_values() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreateSupermarketExpense(user,new("Local Market","Weekly groceries",SupermarketExpenseType.Groceries,64.25m,"eur",new(2026,8,7),"  Used loyalty discount  ")); Assert.Equal(user,result.UserId); Assert.Equal("EUR",result.CurrencyCode); Assert.Equal("Used loyalty discount",result.Notes); }
    [Fact] public async Task Supermarket_expenses_are_user_scoped() { await using var db=Database(); var owner=Guid.NewGuid(); db.SupermarketExpenses.Add(new(){UserId=owner,Store="Market",Description="Groceries",ExpenseType=SupermarketExpenseType.Groceries,Amount=45,ExpenseDate=new(2026,8,7)}); await db.SaveChangesAsync(); Assert.Empty(await new FinanceService(db).SupermarketExpenses(Guid.NewGuid())); }
    [Fact] public async Task Supermarket_expense_rejects_a_non_positive_amount() { await using var db=Database(); await Assert.ThrowsAsync<ArgumentException>(()=>new FinanceService(db).CreateSupermarketExpense(Guid.NewGuid(),new("Market","Groceries",SupermarketExpenseType.Groceries,0,"EUR",new(2026,8,7),null))); }
    [Fact] public async Task Updating_a_supermarket_expense_enforces_ownership() { await using var db=Database(); var owner=Guid.NewGuid(); var expense=new SupermarketExpense{UserId=owner,Store="Market",Description="Groceries",ExpenseType=SupermarketExpenseType.Groceries,Amount=50,ExpenseDate=new(2026,8,7)}; db.Add(expense); await db.SaveChangesAsync(); var service=new FinanceService(db); var updated=await service.UpdateSupermarketExpense(owner,expense.Id,new("Other Market","Food and cleaning",SupermarketExpenseType.HouseholdSupplies,65,"EUR",new(2026,8,8),null)); Assert.Equal(65,updated.Amount); Assert.Equal("Other Market",updated.Store); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.UpdateSupermarketExpense(Guid.NewGuid(),expense.Id,new("Shop","Other",SupermarketExpenseType.Other,10,"EUR",new(2026,8,8),null))); }
    [Fact] public async Task Dashboard_includes_only_supermarket_expenses_from_the_selected_month() { await using var db=Database(); var user=Guid.NewGuid(); db.SupermarketExpenses.AddRange(new(){UserId=user,Store="Market",Description="Groceries",ExpenseType=SupermarketExpenseType.Groceries,Amount=70,ExpenseDate=new(2026,8,2)},new(){UserId=user,Store="Market",Description="Old groceries",ExpenseType=SupermarketExpenseType.Groceries,Amount=40,ExpenseDate=new(2026,7,30)}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Dashboard(user,8,2026); Assert.Contains("monthlyExpenses = 70",result.ToString()); Assert.Contains("supermarketExpenses = 70",result.ToString()); }
}
