using Finora.Api.Data;
using Finora.Api.Features;
using Microsoft.EntityFrameworkCore;

namespace Finora.Api.Tests;

public sealed class FinanceServiceTests
{
    private static FinoraDbContext Database() => new(new DbContextOptionsBuilder<FinoraDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);
    [Fact] public void Registration_validation_requires_a_display_name() { var request=new RegisterRequest("person@example.com","long-password",""); Assert.True(string.IsNullOrWhiteSpace(request.DisplayName)); }
    [Fact] public void Api_finance_routes_require_authentication() { var method=typeof(Endpoints).GetMethod(nameof(Endpoints.MapFinoraEndpoints)); Assert.NotNull(method); }
    [Fact] public async Task Users_cannot_access_another_users_accounts() { await using var db=Database(); var owner=Guid.NewGuid(); db.Accounts.Add(new(){UserId=owner,Name="Private"}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Accounts(Guid.NewGuid()); Assert.Empty(result); }
    [Fact] public async Task Creating_an_account_sets_the_owner() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreateAccount(user,new("Daily",AccountType.CurrentAccount,"eur",100)); Assert.Equal(user,result.UserId); Assert.Equal("EUR",result.CurrencyCode); }
    [Fact] public async Task Creating_a_category_sets_owner_icon_and_normalized_color() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreateCategory(user,new("Dining",CategoryType.Expense,"restaurant","#ab12ef")); Assert.Equal(user,result.UserId); Assert.Equal("restaurant",result.Icon); Assert.Equal("#AB12EF",result.Color); }
    [Fact] public async Task Updating_a_category_enforces_ownership() { await using var db=Database(); var owner=Guid.NewGuid(); var category=new Category{UserId=owner,Name="Dining",CategoryType=CategoryType.Expense,Icon="restaurant",Color="#123456"}; db.Add(category); await db.SaveChangesAsync(); var service=new FinanceService(db); var updated=await service.UpdateCategory(owner,category.Id,new("Restaurants",CategoryType.Expense,"restaurant","#654321")); Assert.Equal("Restaurants",updated.Name); Assert.Equal("#654321",updated.Color); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.UpdateCategory(Guid.NewGuid(),category.Id,new("Other",CategoryType.Expense,"category","#112233"))); }
    [Fact] public async Task Category_rejects_invalid_color_and_duplicate_name_per_type() { await using var db=Database(); var user=Guid.NewGuid(); var service=new FinanceService(db); await Assert.ThrowsAsync<ArgumentException>(()=>service.CreateCategory(user,new("Dining",CategoryType.Expense,"restaurant","red"))); await service.CreateCategory(user,new("Dining",CategoryType.Expense,"restaurant","#123456")); await Assert.ThrowsAsync<ArgumentException>(()=>service.CreateCategory(user,new(" dining ",CategoryType.Expense,"restaurant","#654321"))); }
    [Fact] public async Task Creating_an_expense_transaction_is_user_scoped() { await using var db=Database(); var user=Guid.NewGuid(); var account=new Account{UserId=user,Name="Daily"}; db.Add(account); await db.SaveChangesAsync(); var result=await new FinanceService(db).CreateTransaction(user,new(account.Id,null,TransactionType.Expense,20,"Food",DateOnly.FromDateTime(DateTime.UtcNow),null)); Assert.Equal(TransactionType.Expense,result.TransactionType); Assert.Equal(20,result.Amount); }
    [Fact] public async Task Creating_and_updating_a_budget_enforces_owner_and_expense_category() { await using var db=Database(); var owner=Guid.NewGuid(); var category=new Category{UserId=owner,Name="Food",CategoryType=CategoryType.Expense,Icon="shopping_cart",Color="#123456"}; db.Add(category); await db.SaveChangesAsync(); var service=new FinanceService(db); var budget=await service.CreateBudget(owner,new(category.Id,300,8,2026)); Assert.Equal(owner,budget.UserId); var updated=await service.UpdateBudget(owner,budget.Id,new(category.Id,350,8,2026)); Assert.Equal(350,updated.Amount); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.UpdateBudget(Guid.NewGuid(),budget.Id,new(category.Id,400,8,2026))); }
    [Fact] public async Task Budget_rejects_duplicates_and_income_categories() { await using var db=Database(); var user=Guid.NewGuid(); var expense=new Category{UserId=user,Name="Food",CategoryType=CategoryType.Expense}; var income=new Category{UserId=user,Name="Salary",CategoryType=CategoryType.Income}; db.AddRange(expense,income); await db.SaveChangesAsync(); var service=new FinanceService(db); await service.CreateBudget(user,new(expense.Id,300,8,2026)); await Assert.ThrowsAsync<ArgumentException>(()=>service.CreateBudget(user,new(expense.Id,350,8,2026))); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.CreateBudget(user,new(income.Id,1000,8,2026))); }
    [Fact] public async Task Dashboard_calculates_income_and_expenses() { await using var db=Database(); var user=Guid.NewGuid(); var account=new Account{UserId=user,Name="Daily",InitialBalance=100}; db.Add(account); db.Transactions.AddRange(new(){UserId=user,AccountId=account.Id,TransactionType=TransactionType.Income,Amount=50,Description="Pay",TransactionDate=new(2026,8,1)},new(){UserId=user,AccountId=account.Id,TransactionType=TransactionType.Expense,Amount=25,Description="Food",TransactionDate=new(2026,8,2)}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Dashboard(user,8,2026); Assert.Contains("monthlyIncome = 50",result.ToString()); Assert.Contains("monthlyExpenses = 25",result.ToString()); }
    [Fact] public async Task Creating_a_mortgage_sets_owner_and_normalizes_currency() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreateMortgage(user,new("Home","Bank","Lisbon",250000,220000,3.25m,MortgageRateType.Variable,950,"eur",new(2024,1,1),new(2054,1,1),5)); Assert.Equal(user,result.UserId); Assert.Equal("EUR",result.CurrencyCode); Assert.Equal(220000,result.OutstandingBalance); }
    [Fact] public async Task Mortgages_are_user_scoped() { await using var db=Database(); var owner=Guid.NewGuid(); db.Mortgages.Add(new(){UserId=owner,Name="Private home",Lender="Bank",OriginalPrincipal=100000,OutstandingBalance=90000,MonthlyPayment=500,StartDate=new(2020,1,1),EndDate=new(2050,1,1),PaymentDay=1}); await db.SaveChangesAsync(); Assert.Empty(await new FinanceService(db).Mortgages(Guid.NewGuid())); }
    [Fact] public async Task Mortgage_rejects_balance_above_original_principal() { await using var db=Database(); var service=new FinanceService(db); await Assert.ThrowsAsync<ArgumentException>(()=>service.CreateMortgage(Guid.NewGuid(),new("Home","Bank",null,100000,110000,3,MortgageRateType.Fixed,500,"EUR",new(2024,1,1),new(2054,1,1),1))); }
    [Fact] public async Task Updating_a_mortgage_changes_only_the_owners_record() { await using var db=Database(); var owner=Guid.NewGuid(); var mortgage=new Mortgage{UserId=owner,Name="Home",Lender="Bank",OriginalPrincipal=100000,OutstandingBalance=90000,InterestRate=3,MonthlyPayment=500,StartDate=new(2020,1,1),EndDate=new(2050,1,1),PaymentDay=1}; db.Add(mortgage); await db.SaveChangesAsync(); var service=new FinanceService(db); var updated=await service.UpdateMortgage(owner,mortgage.Id,new("Home","New bank",null,100000,80000,2.5m,MortgageRateType.Fixed,475,"EUR",new(2020,1,1),new(2050,1,1),2)); Assert.Equal(80000,updated.OutstandingBalance); Assert.Equal("New bank",updated.Lender); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.UpdateMortgage(Guid.NewGuid(),mortgage.Id,new("Home","Other",null,100000,70000,2,MortgageRateType.Fixed,450,"EUR",new(2020,1,1),new(2050,1,1),2))); }
    [Fact] public async Task Dashboard_includes_active_mortgage_payment_as_an_expense() { await using var db=Database(); var user=Guid.NewGuid(); db.Mortgages.Add(new(){UserId=user,Name="Home",Lender="Bank",OriginalPrincipal=100000,OutstandingBalance=90000,MonthlyPayment=500,StartDate=new(2020,1,1),EndDate=new(2050,1,1),PaymentDay=1}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Dashboard(user,8,2026); Assert.Contains("monthlyExpenses = 500",result.ToString()); Assert.Contains("mortgageExpenses = 500",result.ToString()); }
    [Fact] public async Task Creating_a_household_bill_sets_owner_and_normalizes_currency() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreateHouseholdBill(user,new("Home internet","Fiber Co",HouseholdBillType.Internet,39.99m,"eur",12,new(2026,1,1),null,true)); Assert.Equal(user,result.UserId); Assert.Equal("EUR",result.CurrencyCode); Assert.Equal(HouseholdBillType.Internet,result.BillType); }
    [Fact] public async Task Household_bill_can_be_marked_and_updated_as_recurring() { await using var db=Database(); var user=Guid.NewGuid(); var service=new FinanceService(db); var bill=await service.CreateHouseholdBill(user,new("Internet","ISP",HouseholdBillType.Internet,40,"EUR",5,new(2026,1,1),null,true,true)); Assert.True(bill.IsRecurring); var updated=await service.UpdateHouseholdBill(user,bill.Id,new("Internet","ISP",HouseholdBillType.Internet,40,"EUR",5,new(2026,1,1),null,true,false)); Assert.False(updated.IsRecurring); }
    [Fact] public async Task Household_bills_are_user_scoped() { await using var db=Database(); var owner=Guid.NewGuid(); db.HouseholdBills.Add(new(){UserId=owner,Name="Water",Provider="Utility",BillType=HouseholdBillType.Water,Amount=25,BillingDay=10,StartDate=new(2026,1,1)}); await db.SaveChangesAsync(); Assert.Empty(await new FinanceService(db).HouseholdBills(Guid.NewGuid())); }
    [Fact] public async Task Household_bill_rejects_an_invalid_billing_day() { await using var db=Database(); var service=new FinanceService(db); await Assert.ThrowsAsync<ArgumentException>(()=>service.CreateHouseholdBill(Guid.NewGuid(),new("Gas","Provider",HouseholdBillType.Gas,30,"EUR",32,new(2026,1,1),null,true))); }
    [Fact] public async Task Updating_a_household_bill_enforces_ownership() { await using var db=Database(); var owner=Guid.NewGuid(); var bill=new HouseholdBill{UserId=owner,Name="Mobile",Provider="Carrier",BillType=HouseholdBillType.MobilePlan,Amount=20,BillingDay=1,StartDate=new(2026,1,1)}; db.Add(bill); await db.SaveChangesAsync(); var service=new FinanceService(db); var updated=await service.UpdateHouseholdBill(owner,bill.Id,new("Mobile family","Carrier",HouseholdBillType.MobilePlan,35,"EUR",5,new(2026,1,1),null,true)); Assert.Equal(35,updated.Amount); Assert.Equal(5,updated.BillingDay); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.UpdateHouseholdBill(Guid.NewGuid(),bill.Id,new("Other","Carrier",HouseholdBillType.MobilePlan,10,"EUR",1,new(2026,1,1),null,true))); }
    [Fact] public async Task Dashboard_includes_only_active_household_bills_for_the_month() { await using var db=Database(); var user=Guid.NewGuid(); db.HouseholdBills.AddRange(new(){UserId=user,Name="Electricity",Provider="Power",BillType=HouseholdBillType.Electricity,Amount=60,BillingDay=8,StartDate=new(2026,1,1),IsActive=true},new(){UserId=user,Name="Old internet",Provider="ISP",BillType=HouseholdBillType.Internet,Amount=40,BillingDay=1,StartDate=new(2025,1,1),EndDate=new(2026,7,31),IsActive=true},new(){UserId=user,Name="Paused gas",Provider="Gas",BillType=HouseholdBillType.Gas,Amount=30,BillingDay=2,StartDate=new(2026,1,1),IsActive=false}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Dashboard(user,8,2026); Assert.Contains("monthlyExpenses = 60",result.ToString()); Assert.Contains("householdBillExpenses = 60",result.ToString()); }
    [Fact] public async Task Creating_a_medical_expense_sets_owner_and_normalizes_values() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreateMedicalExpense(user,new("Prescription medicine","Local Pharmacy",MedicalExpenseType.Pharmacy,18.50m,"eur",new(2026,8,7),"  Monthly prescription  ",true)); Assert.Equal(user,result.UserId); Assert.Equal("EUR",result.CurrencyCode); Assert.Equal("Monthly prescription",result.Notes); Assert.True(result.IsReimbursable); }
    [Fact] public async Task Medical_expenses_are_user_scoped() { await using var db=Database(); var owner=Guid.NewGuid(); db.MedicalExpenses.Add(new(){UserId=owner,Description="Exam",Provider="Clinic",ExpenseType=MedicalExpenseType.Exam,Amount=75,ExpenseDate=new(2026,8,7)}); await db.SaveChangesAsync(); Assert.Empty(await new FinanceService(db).MedicalExpenses(Guid.NewGuid())); }
    [Fact] public async Task Medical_expense_rejects_a_non_positive_amount() { await using var db=Database(); await Assert.ThrowsAsync<ArgumentException>(()=>new FinanceService(db).CreateMedicalExpense(Guid.NewGuid(),new("Appointment","Clinic",MedicalExpenseType.Appointment,0,"EUR",new(2026,8,7),null,false))); }
    [Fact] public async Task Updating_a_medical_expense_enforces_ownership() { await using var db=Database(); var owner=Guid.NewGuid(); var expense=new MedicalExpense{UserId=owner,Description="Exam",Provider="Clinic",ExpenseType=MedicalExpenseType.Exam,Amount=75,ExpenseDate=new(2026,8,7)}; db.Add(expense); await db.SaveChangesAsync(); var service=new FinanceService(db); var updated=await service.UpdateMedicalExpense(owner,expense.Id,new("Blood exam","Lab",MedicalExpenseType.Exam,45,"EUR",new(2026,8,8),null,true)); Assert.Equal(45,updated.Amount); Assert.Equal("Lab",updated.Provider); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.UpdateMedicalExpense(Guid.NewGuid(),expense.Id,new("Other","Clinic",MedicalExpenseType.Other,10,"EUR",new(2026,8,8),null,false))); }
    [Fact] public async Task Dashboard_includes_only_medical_expenses_from_the_selected_month() { await using var db=Database(); var user=Guid.NewGuid(); db.MedicalExpenses.AddRange(new(){UserId=user,Description="Appointment",Provider="Clinic",ExpenseType=MedicalExpenseType.Appointment,Amount=50,ExpenseDate=new(2026,8,2)},new(){UserId=user,Description="Old exam",Provider="Lab",ExpenseType=MedicalExpenseType.Exam,Amount=80,ExpenseDate=new(2026,7,30)}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Dashboard(user,8,2026); Assert.Contains("monthlyExpenses = 50",result.ToString()); Assert.Contains("medicalExpenses = 50",result.ToString()); }
    [Fact] public async Task Creating_a_supermarket_expense_sets_owner_and_normalizes_values() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreateSupermarketExpense(user,new("Local Market","Weekly groceries",SupermarketExpenseType.Groceries,64.25m,"eur",new(2026,8,7),"  Used loyalty discount  ")); Assert.Equal(user,result.UserId); Assert.Equal("EUR",result.CurrencyCode); Assert.Equal("Used loyalty discount",result.Notes); }
    [Fact] public async Task Supermarket_expenses_are_user_scoped() { await using var db=Database(); var owner=Guid.NewGuid(); db.SupermarketExpenses.Add(new(){UserId=owner,Store="Market",Description="Groceries",ExpenseType=SupermarketExpenseType.Groceries,Amount=45,ExpenseDate=new(2026,8,7)}); await db.SaveChangesAsync(); Assert.Empty(await new FinanceService(db).SupermarketExpenses(Guid.NewGuid())); }
    [Fact] public async Task Supermarket_expense_rejects_a_non_positive_amount() { await using var db=Database(); await Assert.ThrowsAsync<ArgumentException>(()=>new FinanceService(db).CreateSupermarketExpense(Guid.NewGuid(),new("Market","Groceries",SupermarketExpenseType.Groceries,0,"EUR",new(2026,8,7),null))); }
    [Fact] public async Task Updating_a_supermarket_expense_enforces_ownership() { await using var db=Database(); var owner=Guid.NewGuid(); var expense=new SupermarketExpense{UserId=owner,Store="Market",Description="Groceries",ExpenseType=SupermarketExpenseType.Groceries,Amount=50,ExpenseDate=new(2026,8,7)}; db.Add(expense); await db.SaveChangesAsync(); var service=new FinanceService(db); var updated=await service.UpdateSupermarketExpense(owner,expense.Id,new("Other Market","Food and cleaning",SupermarketExpenseType.HouseholdSupplies,65,"EUR",new(2026,8,8),null)); Assert.Equal(65,updated.Amount); Assert.Equal("Other Market",updated.Store); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.UpdateSupermarketExpense(Guid.NewGuid(),expense.Id,new("Shop","Other",SupermarketExpenseType.Other,10,"EUR",new(2026,8,8),null))); }
    [Fact] public async Task Dashboard_includes_only_supermarket_expenses_from_the_selected_month() { await using var db=Database(); var user=Guid.NewGuid(); db.SupermarketExpenses.AddRange(new(){UserId=user,Store="Market",Description="Groceries",ExpenseType=SupermarketExpenseType.Groceries,Amount=70,ExpenseDate=new(2026,8,2)},new(){UserId=user,Store="Market",Description="Old groceries",ExpenseType=SupermarketExpenseType.Groceries,Amount=40,ExpenseDate=new(2026,7,30)}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Dashboard(user,8,2026); Assert.Contains("monthlyExpenses = 70",result.ToString()); Assert.Contains("supermarketExpenses = 70",result.ToString()); }
    [Fact] public async Task Creating_an_education_expense_sets_owner_and_normalizes_values() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreatePersonalExpense(user,new(PersonalExpenseArea.Education,PersonalExpenseType.Course,"C# course","Learning Platform",49.99m,"eur",new(2026,8,7),"  Annual access  ")); Assert.Equal(user,result.UserId); Assert.Equal("EUR",result.CurrencyCode); Assert.Equal("Annual access",result.Notes); Assert.Equal(PersonalExpenseArea.Education,result.Area); }
    [Fact] public async Task Personal_expenses_are_scoped_by_user_and_area() { await using var db=Database(); var owner=Guid.NewGuid(); db.PersonalExpenses.AddRange(new(){UserId=owner,Area=PersonalExpenseArea.Education,ExpenseType=PersonalExpenseType.Book,Description="Book",Provider="Bookshop",Amount=20,ExpenseDate=new(2026,8,7)},new(){UserId=owner,Area=PersonalExpenseArea.Entertainment,ExpenseType=PersonalExpenseType.Game,Description="Game",Provider="Store",Amount=30,ExpenseDate=new(2026,8,7)}); await db.SaveChangesAsync(); var service=new FinanceService(db); Assert.Single(await service.PersonalExpenses(owner,PersonalExpenseArea.Education)); Assert.Empty(await service.PersonalExpenses(Guid.NewGuid(),PersonalExpenseArea.Education)); }
    [Fact] public async Task Personal_expense_rejects_a_type_from_the_wrong_area() { await using var db=Database(); await Assert.ThrowsAsync<ArgumentException>(()=>new FinanceService(db).CreatePersonalExpense(Guid.NewGuid(),new(PersonalExpenseArea.Education,PersonalExpenseType.Game,"Game","Store",20,"EUR",new(2026,8,7),null))); }
    [Fact] public async Task Updating_a_personal_expense_enforces_ownership() { await using var db=Database(); var owner=Guid.NewGuid(); var expense=new PersonalExpense{UserId=owner,Area=PersonalExpenseArea.Entertainment,ExpenseType=PersonalExpenseType.Movie,Description="Cinema",Provider="Theatre",Amount=15,ExpenseDate=new(2026,8,7)}; db.Add(expense); await db.SaveChangesAsync(); var service=new FinanceService(db); var updated=await service.UpdatePersonalExpense(owner,expense.Id,new(PersonalExpenseArea.Entertainment,PersonalExpenseType.Event,"Concert","Venue",45,"EUR",new(2026,8,8),null)); Assert.Equal(45,updated.Amount); Assert.Equal(PersonalExpenseType.Event,updated.ExpenseType); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.UpdatePersonalExpense(Guid.NewGuid(),expense.Id,new(PersonalExpenseArea.Entertainment,PersonalExpenseType.Movie,"Other","Cinema",10,"EUR",new(2026,8,8),null))); }
    [Fact] public async Task Creating_a_pet_expense_sets_owner_and_normalizes_values() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreatePetExpense(user,new("Luna","Annual vaccination","Vet Clinic",PetExpenseType.Veterinary,45,"eur",new(2026,8,7),"  Booster  ")); Assert.Equal(user,result.UserId); Assert.Equal("EUR",result.CurrencyCode); Assert.Equal("Booster",result.Notes); Assert.Equal("Luna",result.PetName); }
    [Fact] public async Task Pet_expenses_are_user_scoped_and_updates_enforce_ownership() { await using var db=Database(); var owner=Guid.NewGuid(); var expense=new PetExpense{UserId=owner,PetName="Luna",Description="Food",Provider="Pet shop",ExpenseType=PetExpenseType.Food,Amount=30,ExpenseDate=new(2026,8,7)}; db.Add(expense); await db.SaveChangesAsync(); var service=new FinanceService(db); Assert.Empty(await service.PetExpenses(Guid.NewGuid())); var updated=await service.UpdatePetExpense(owner,expense.Id,new("Luna","Dry food","Other shop",PetExpenseType.Food,35,"EUR",new(2026,8,8),null)); Assert.Equal(35,updated.Amount); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.UpdatePetExpense(Guid.NewGuid(),expense.Id,new("Luna","Food","Shop",PetExpenseType.Food,10,"EUR",new(2026,8,8),null))); }
    [Fact] public async Task Dashboard_includes_only_pet_expenses_from_the_selected_month() { await using var db=Database(); var user=Guid.NewGuid(); db.PetExpenses.AddRange(new(){UserId=user,PetName="Luna",Description="Vet",Provider="Clinic",ExpenseType=PetExpenseType.Veterinary,Amount=55,ExpenseDate=new(2026,8,2)},new(){UserId=user,PetName="Luna",Description="Old food",Provider="Shop",ExpenseType=PetExpenseType.Food,Amount=25,ExpenseDate=new(2026,7,30)}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Dashboard(user,8,2026); Assert.Contains("monthlyExpenses = 55",result.ToString()); Assert.Contains("petExpenses = 55",result.ToString()); }
    [Fact] public async Task Creating_a_loan_sets_owner_and_normalizes_currency() { await using var db=Database(); var user=Guid.NewGuid(); var result=await new FinanceService(db).CreateFinancialProduct(user,FinancialProductType.Loan,new("Car loan","Bank",null,8000,null,12000,5.2m,250,15,new(2025,1,1),new(2029,1,1),null,"eur",true,null)); Assert.Equal(user,result.UserId); Assert.Equal("EUR",result.CurrencyCode); Assert.Equal(FinancialProductType.Loan,result.ProductType); }
    [Fact] public async Task Financial_products_are_scoped_by_user_and_type() { await using var db=Database(); var user=Guid.NewGuid(); db.FinancialProducts.AddRange(new(){UserId=user,ProductType=FinancialProductType.CreditCard,Name="Rewards",Institution="Bank",CurrentBalance=200,CreditLimit=2000},new(){UserId=user,ProductType=FinancialProductType.DebitCard,Name="Daily",Institution="Bank",CurrentBalance=500}); await db.SaveChangesAsync(); var service=new FinanceService(db); Assert.Single(await service.FinancialProducts(user,FinancialProductType.CreditCard)); Assert.Single(await service.FinancialProducts(user,FinancialProductType.DebitCard)); Assert.Empty(await service.FinancialProducts(Guid.NewGuid(),FinancialProductType.CreditCard)); }
    [Fact] public async Task Updating_a_card_enforces_ownership_and_limits() { await using var db=Database(); var owner=Guid.NewGuid(); var card=new FinancialProduct{UserId=owner,ProductType=FinancialProductType.CreditCard,Name="Rewards",Institution="Bank",CurrentBalance=100,CreditLimit=1000}; db.Add(card); await db.SaveChangesAsync(); var service=new FinanceService(db); var updated=await service.UpdateFinancialProduct(owner,card.Id,FinancialProductType.CreditCard,new("Rewards","Bank","1234",250,1500,null,null,null,10,null,null,new(2029,1,1),"EUR",true,null)); Assert.Equal(250,updated.CurrentBalance); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.UpdateFinancialProduct(Guid.NewGuid(),card.Id,FinancialProductType.CreditCard,new("Other","Bank","1234",10,500,null,null,null,1,null,null,null,"EUR",true,null))); await Assert.ThrowsAsync<ArgumentException>(()=>service.CreateFinancialProduct(owner,FinancialProductType.CreditCard,new("Bad","Bank",null,600,500,null,null,null,1,null,null,null,"EUR",true,null))); }
    [Fact] public async Task Creating_and_updating_an_investment_tracks_value_and_owner() { await using var db=Database(); var owner=Guid.NewGuid(); var service=new FinanceService(db); var investment=await service.CreateFinancialProduct(owner,FinancialProductType.Investment,new("Index fund","Broker",null,1250,null,1000,null,null,null,new(2025,1,1),null,null,"eur",true,"Long term")); Assert.Equal("EUR",investment.CurrencyCode); Assert.Equal(1000,investment.OriginalPrincipal); var updated=await service.UpdateFinancialProduct(owner,investment.Id,FinancialProductType.Investment,new("Index fund","Broker",null,1400,null,1100,null,null,null,new(2025,1,1),null,null,"EUR",true,null)); Assert.Equal(1400,updated.CurrentBalance); Assert.Empty(await service.FinancialProducts(Guid.NewGuid(),FinancialProductType.Investment)); await Assert.ThrowsAsync<KeyNotFoundException>(()=>service.UpdateFinancialProduct(Guid.NewGuid(),investment.Id,FinancialProductType.Investment,new("Other","Broker",null,1,null,1,null,null,null,new(2025,1,1),null,null,"EUR",true,null))); }
    [Fact] public async Task Dashboard_separates_education_and_entertainment_for_the_selected_month() { await using var db=Database(); var user=Guid.NewGuid(); db.PersonalExpenses.AddRange(new(){UserId=user,Area=PersonalExpenseArea.Education,ExpenseType=PersonalExpenseType.Book,Description="Book",Provider="Shop",Amount=25,ExpenseDate=new(2026,8,2)},new(){UserId=user,Area=PersonalExpenseArea.Entertainment,ExpenseType=PersonalExpenseType.Game,Description="Game",Provider="Store",Amount=35,ExpenseDate=new(2026,8,3)},new(){UserId=user,Area=PersonalExpenseArea.Education,ExpenseType=PersonalExpenseType.Course,Description="Old course",Provider="School",Amount=80,ExpenseDate=new(2026,7,30)}); await db.SaveChangesAsync(); var result=await new FinanceService(db).Dashboard(user,8,2026); Assert.Contains("monthlyExpenses = 60",result.ToString()); Assert.Contains("educationExpenses = 25",result.ToString()); Assert.Contains("entertainmentExpenses = 35",result.ToString()); }
}
