import { CurrencyPipe, DatePipe } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, computed, inject, OnInit, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { forkJoin } from 'rxjs';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';

interface Budget { id:string; categoryId:string; amount:number; month:number; year:number; createdAtUtc:string; updatedAtUtc:string; }
interface Category { id:string; name:string; categoryType:number; icon:string; color:string; }

@Component({
  standalone:true,
  imports:[CurrencyPipe,DatePipe,ReactiveFormsModule,MatButtonModule,MatCardModule,MatFormFieldModule,MatIconModule,MatInputModule,MatSelectModule],
  template:`
    <header><p class="eyebrow">PLAN YOUR SPENDING</p><h1>Budgets</h1><p>Set monthly limits for your expense categories and adjust them whenever your plans change.</p></header>
    <section class="summary" aria-label="Budget summary"><mat-card><span class="summary-icon"><mat-icon>account_balance_wallet</mat-icon></span><span>{{periodLabel()}} total</span><strong>{{selectedTotal()|currency:'EUR'}}</strong></mat-card><mat-card><span class="summary-icon"><mat-icon>category</mat-icon></span><span>Categories budgeted</span><strong>{{visibleBudgets().length}}</strong></mat-card></section>
    <div class="layout"><mat-card class="form-card"><h2>{{editingId()?'Edit budget':'Create a budget'}}</h2><form [formGroup]="form" (ngSubmit)="save()"><div class="fields">
      <mat-form-field class="wide"><mat-label>Expense category</mat-label><mat-select formControlName="categoryId">@for(category of expenseCategories();track category.id){<mat-option [value]="category.id"><mat-icon [style.color]="category.color">{{category.icon}}</mat-icon>{{category.name}}</mat-option>}</mat-select>@if(!expenseCategories().length){<mat-hint>Create an expense category first</mat-hint>}</mat-form-field>
      <mat-form-field><mat-label>Monthly amount</mat-label><input matInput type="number" min="0.01" step="0.01" formControlName="amount"><span matTextSuffix>EUR</span></mat-form-field>
      <mat-form-field><mat-label>Month</mat-label><mat-select formControlName="month">@for(month of months;track month.value){<mat-option [value]="month.value">{{month.label}}</mat-option>}</mat-select></mat-form-field>
      <mat-form-field><mat-label>Year</mat-label><input matInput type="number" min="2000" max="2200" formControlName="year"></mat-form-field>
    </div>@if(error()){<p class="error">{{error()}}</p>}<div class="actions"><button mat-flat-button type="submit" [disabled]="form.invalid||saving()||!expenseCategories().length">{{saving()?'Saving…':editingId()?'Save changes':'Create budget'}}</button>@if(editingId()){<button mat-button type="button" (click)="cancelEdit()">Cancel</button>}</div></form></mat-card>
    <section class="budgets" aria-live="polite"><div class="period-filter"><mat-form-field><mat-label>View month</mat-label><mat-select [value]="viewMonth()" (selectionChange)="viewMonth.set($event.value)">@for(month of months;track month.value){<mat-option [value]="month.value">{{month.label}}</mat-option>}</mat-select></mat-form-field><mat-form-field><mat-label>View year</mat-label><input matInput type="number" min="2000" max="2200" [value]="viewYear()" (change)="setViewYear($event)"></mat-form-field></div>
      @if(loading()){<mat-card class="empty">Loading budgets…</mat-card>}@else if(!visibleBudgets().length){<mat-card class="empty"><mat-icon>savings</mat-icon><h2>No budgets for {{periodLabel()}}</h2><p>Create a monthly budget for one of your expense categories.</p></mat-card>}@for(budget of visibleBudgets();track budget.id){@let category=categoryFor(budget.categoryId);<mat-card class="budget-card"><div class="budget-head"><span class="category-icon" [style.background]="category?.color||'#607D8B'"><mat-icon>{{category?.icon||'category'}}</mat-icon></span><div><h2>{{category?.name||'Unknown category'}}</h2><p>{{months[budget.month-1].label}} {{budget.year}}</p></div><div class="card-actions"><button mat-icon-button (click)="edit(budget)" [attr.aria-label]="'Edit '+(category?.name||'budget')"><mat-icon>edit</mat-icon></button><button mat-icon-button (click)="remove(budget)" [attr.aria-label]="'Delete '+(category?.name||'budget')"><mat-icon>delete_outline</mat-icon></button></div></div><strong>{{budget.amount|currency:'EUR'}}</strong><span class="caption">monthly limit</span><p class="updated">Updated {{budget.updatedAtUtc|date:'mediumDate'}}</p></mat-card>}</section></div>`,
  styles:[`header h1{font-size:clamp(1.8rem,4vw,2.6rem);margin:.15rem 0}.eyebrow{letter-spacing:.15em;color:#397454;font-weight:700}.summary{display:grid;grid-template-columns:repeat(2,minmax(220px,320px));gap:1rem;margin:2rem 0}.summary mat-card{display:grid;grid-template-columns:auto 1fr;align-items:center;gap:.15rem .9rem;padding:1rem 1.2rem}.summary-icon{grid-row:1/3;display:grid;place-items:center;width:42px;height:42px;border-radius:13px;background:#e3f1e6;color:#397454}.summary span{color:#68766f}.summary strong{font-size:1.4rem}.layout{display:grid;grid-template-columns:minmax(320px,.85fr) minmax(0,1.15fr);gap:1.25rem;align-items:start}mat-card{padding:1.3rem}.form-card{position:sticky;top:84px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:0 1rem}.wide{grid-column:1/-1}.actions{display:flex;gap:.5rem;margin-top:1rem}.actions button:first-child{flex:1}.error{color:#b3261e;font-size:.85rem}.budgets{display:grid;gap:1rem}.period-filter{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.budget-head{display:grid;grid-template-columns:auto 1fr auto;gap:.8rem}.category-icon{display:grid;place-items:center;width:46px;height:46px;border-radius:14px;color:#fff}.budget-card h2{margin:0;font-size:1.08rem}.budget-card p{margin:.2rem 0;color:#68766f}.budget-card>strong{display:block;margin-top:1.2rem;font-size:1.8rem}.caption,.updated{color:#68766f;font-size:.78rem}.updated{padding-top:.8rem;border-top:1px solid #e3e9e5}.card-actions{display:flex}.empty{min-height:220px;display:grid;place-content:center;text-align:center;color:#68766f}.empty>mat-icon{margin:auto;font-size:42px;width:42px;height:42px;color:#397454}@media(max-width:900px){.layout{grid-template-columns:1fr}.form-card{position:static}}@media(max-width:560px){.summary,.fields,.period-filter{grid-template-columns:1fr}.wide{grid-column:auto}.budget-head{grid-template-columns:auto 1fr}.card-actions{grid-column:2}}`]
})
export class BudgetsComponent implements OnInit {
  private readonly http=inject(HttpClient); readonly budgets=signal<Budget[]>([]); readonly categories=signal<Category[]>([]); readonly loading=signal(true); readonly saving=signal(false); readonly editingId=signal<string|null>(null); readonly error=signal(''); readonly today=new Date(); readonly viewMonth=signal(this.today.getMonth()+1); readonly viewYear=signal(this.today.getFullYear());
  readonly months=Array.from({length:12},(_,index)=>({value:index+1,label:new Intl.DateTimeFormat('en',{month:'long'}).format(new Date(2024,index,1))})); readonly expenseCategories=computed(()=>this.categories().filter(x=>x.categoryType===1)); readonly visibleBudgets=computed(()=>this.budgets().filter(x=>x.month===this.viewMonth()&&x.year===this.viewYear()).sort((a,b)=>(this.categoryFor(a.categoryId)?.name??'').localeCompare(this.categoryFor(b.categoryId)?.name??''))); readonly selectedTotal=computed(()=>this.visibleBudgets().reduce((sum,item)=>sum+item.amount,0));
  readonly form=new FormGroup({categoryId:new FormControl('',{nonNullable:true,validators:[Validators.required]}),amount:new FormControl<number|null>(null,[Validators.required,Validators.min(.01)]),month:new FormControl(this.today.getMonth()+1,{nonNullable:true,validators:[Validators.required,Validators.min(1),Validators.max(12)]}),year:new FormControl(this.today.getFullYear(),{nonNullable:true,validators:[Validators.required,Validators.min(2000),Validators.max(2200)]})});
  ngOnInit(){forkJoin({budgets:this.http.get<Budget[]>('/api/budgets'),categories:this.http.get<Category[]>('/api/categories')}).subscribe({next:value=>{this.budgets.set(value.budgets);this.categories.set(value.categories);this.loading.set(false)},error:()=>this.loading.set(false)});} categoryFor(id:string){return this.categories().find(x=>x.id===id);} periodLabel(){return `${this.months[this.viewMonth()-1].label} ${this.viewYear()}`;} setViewYear(event:Event){const year=Number((event.target as HTMLInputElement).value);if(year>=2000&&year<=2200)this.viewYear.set(year);}
  save(){if(this.form.invalid)return;this.saving.set(true);this.error.set('');const id=this.editingId();const payload=this.form.getRawValue();const request=id?this.http.put<Budget>(`/api/budgets/${id}`,payload):this.http.post<Budget>('/api/budgets',payload);request.subscribe({next:x=>{this.budgets.update(items=>id?items.map(item=>item.id===id?x:item):[...items,x]);this.viewMonth.set(x.month);this.viewYear.set(x.year);this.cancelEdit();this.saving.set(false)},error:response=>{this.error.set(response.error?.detail??response.error?.title??'Could not save this budget.');this.saving.set(false)}});}
  edit(x:Budget){this.editingId.set(x.id);this.error.set('');this.form.setValue({categoryId:x.categoryId,amount:x.amount,month:x.month,year:x.year});window.scrollTo({top:0,behavior:'smooth'});} cancelEdit(){this.editingId.set(null);this.error.set('');this.form.reset({categoryId:'',amount:null,month:this.viewMonth(),year:this.viewYear()});}
  remove(x:Budget){const category=this.categoryFor(x.categoryId);if(!confirm(`Delete the ${category?.name??''} budget for ${this.months[x.month-1].label} ${x.year}?`))return;this.http.delete(`/api/budgets/${x.id}`).subscribe(()=>this.budgets.update(items=>items.filter(item=>item.id!==x.id)));}
}
