using System.Security.Claims;
using Finora.Api.Data;
using Microsoft.EntityFrameworkCore;

namespace Finora.Api.Features;

public sealed record AccountRequest(string Name, AccountType AccountType, string CurrencyCode, decimal InitialBalance);
public sealed record CategoryRequest(string Name, CategoryType CategoryType, string? Icon);
public sealed record TransactionRequest(Guid AccountId, Guid? CategoryId, TransactionType TransactionType, decimal Amount, string Description, DateOnly TransactionDate, string? Notes);
public sealed record BudgetRequest(Guid CategoryId, decimal Amount, int Month, int Year);
public sealed record RecurringRequest(Guid AccountId, Guid? CategoryId, TransactionType TransactionType, decimal Amount, string Description, RecurringFrequency Frequency, DateOnly StartDate, DateOnly NextOccurrenceDate, DateOnly? EndDate, bool IsActive);
public sealed record Page<T>(IReadOnlyList<T> Items, int PageNumber, int PageSize, int TotalCount);

public sealed class FinanceService(FinoraDbContext db)
{
    public static Guid UserId(ClaimsPrincipal user) => Guid.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!);
    public Task<List<Account>> Accounts(Guid userId) => db.Accounts.AsNoTracking().Where(x => x.UserId == userId).OrderBy(x => x.Name).ToListAsync();
    public async Task<Account> CreateAccount(Guid userId, AccountRequest r) { if (string.IsNullOrWhiteSpace(r.Name) || r.CurrencyCode.Length != 3) throw new ArgumentException("Name and a three-letter currency are required."); var x = new Account { UserId=userId, Name=r.Name.Trim(), AccountType=r.AccountType, CurrencyCode=r.CurrencyCode.ToUpperInvariant(), InitialBalance=r.InitialBalance }; db.Add(x); await db.SaveChangesAsync(); return x; }
    public Task<List<Category>> Categories(Guid userId) => db.Categories.AsNoTracking().Where(x => x.UserId == userId).OrderBy(x => x.Name).ToListAsync();
    public async Task<Category> CreateCategory(Guid userId, CategoryRequest r) { if (string.IsNullOrWhiteSpace(r.Name)) throw new ArgumentException("Name is required."); var x = new Category { UserId=userId, Name=r.Name.Trim(), CategoryType=r.CategoryType, Icon=r.Icon }; db.Add(x); await db.SaveChangesAsync(); return x; }
    public async Task<Page<Transaction>> Transactions(Guid userId, int page, int size, Guid? account, Guid? category, TransactionType? type, DateOnly? start, DateOnly? end, string? search) { var q=db.Transactions.AsNoTracking().Where(x=>x.UserId==userId); if(account.HasValue)q=q.Where(x=>x.AccountId==account); if(category.HasValue)q=q.Where(x=>x.CategoryId==category); if(type.HasValue)q=q.Where(x=>x.TransactionType==type); if(start.HasValue)q=q.Where(x=>x.TransactionDate>=start); if(end.HasValue)q=q.Where(x=>x.TransactionDate<=end); if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.Description.Contains(search)); var count=await q.CountAsync(); var items=await q.OrderByDescending(x=>x.TransactionDate).Skip((page-1)*size).Take(size).ToListAsync(); return new(items,page,size,count); }
    public async Task<Transaction> CreateTransaction(Guid userId, TransactionRequest r) { if(r.Amount<=0)throw new ArgumentException("Amount must be positive."); if(!await db.Accounts.AnyAsync(x=>x.Id==r.AccountId&&x.UserId==userId))throw new KeyNotFoundException("Account not found."); if(r.CategoryId.HasValue&&!await db.Categories.AnyAsync(x=>x.Id==r.CategoryId&&x.UserId==userId))throw new KeyNotFoundException("Category not found."); var x=new Transaction { UserId=userId, AccountId=r.AccountId, CategoryId=r.CategoryId, TransactionType=r.TransactionType, Amount=r.Amount, Description=r.Description.Trim(), TransactionDate=r.TransactionDate, Notes=r.Notes }; db.Add(x); await db.SaveChangesAsync(); return x; }
    public Task<List<Budget>> Budgets(Guid userId) => db.Budgets.AsNoTracking().Where(x=>x.UserId==userId).ToListAsync();
    public async Task<Budget> CreateBudget(Guid userId, BudgetRequest r) { if(r.Amount<=0||r.Month is <1 or >12)throw new ArgumentException("Invalid budget."); if(!await db.Categories.AnyAsync(x=>x.Id==r.CategoryId&&x.UserId==userId))throw new KeyNotFoundException("Category not found."); var x=new Budget { UserId=userId, CategoryId=r.CategoryId, Amount=r.Amount, Month=r.Month, Year=r.Year }; db.Add(x); await db.SaveChangesAsync(); return x; }
    public Task<List<RecurringTransaction>> Recurring(Guid userId) => db.RecurringTransactions.AsNoTracking().Where(x=>x.UserId==userId).ToListAsync();
    public async Task<RecurringTransaction> CreateRecurring(Guid userId, RecurringRequest r) { if(r.Amount<=0)throw new ArgumentException("Amount must be positive."); if(!await db.Accounts.AnyAsync(x=>x.Id==r.AccountId&&x.UserId==userId))throw new KeyNotFoundException("Account not found."); var x=new RecurringTransaction { UserId=userId, AccountId=r.AccountId, CategoryId=r.CategoryId, TransactionType=r.TransactionType, Amount=r.Amount, Description=r.Description, Frequency=r.Frequency, StartDate=r.StartDate, NextOccurrenceDate=r.NextOccurrenceDate, EndDate=r.EndDate, IsActive=r.IsActive }; db.Add(x); await db.SaveChangesAsync(); return x; }
    public async Task<object> Dashboard(Guid userId,int month,int year) { var tx=await db.Transactions.AsNoTracking().Where(x=>x.UserId==userId&&x.TransactionDate.Month==month&&x.TransactionDate.Year==year).ToListAsync(); var income=tx.Where(x=>x.TransactionType==TransactionType.Income).Sum(x=>x.Amount); var expenses=tx.Where(x=>x.TransactionType==TransactionType.Expense).Sum(x=>x.Amount); var budgets=await db.Budgets.Where(x=>x.UserId==userId&&x.Month==month&&x.Year==year).SumAsync(x=>(decimal?)x.Amount)??0; var initial=await db.Accounts.Where(x=>x.UserId==userId&&!x.IsArchived).SumAsync(x=>(decimal?)x.InitialBalance)??0; var categoryNames=await db.Categories.Where(x=>x.UserId==userId).ToDictionaryAsync(x=>x.Id,x=>x.Name); return new { totalBalance=initial+income-expenses, monthlyIncome=income, monthlyExpenses=expenses, remainingBudget=budgets-expenses, recentTransactions=tx.OrderByDescending(x=>x.TransactionDate).Take(5), spendingByCategory=tx.Where(x=>x.TransactionType==TransactionType.Expense).GroupBy(x=>x.CategoryId).Select(g=>new { category=g.Key.HasValue&&categoryNames.TryGetValue(g.Key.Value,out var n)?n:"Uncategorized", amount=g.Sum(x=>x.Amount)}), cashFlow=new[]{new { month, year, income, expenses }} }; }
}
