using System.Security.Claims;
using Finora.Api.Data;
using Microsoft.EntityFrameworkCore;

namespace Finora.Api.Features;

public sealed record AccountRequest(string Name, AccountType AccountType, string CurrencyCode, decimal InitialBalance);
public sealed record CategoryRequest(string Name, CategoryType CategoryType, string? Icon);
public sealed record TransactionRequest(Guid AccountId, Guid? CategoryId, TransactionType TransactionType, decimal Amount, string Description, DateOnly TransactionDate, string? Notes);
public sealed record BudgetRequest(Guid CategoryId, decimal Amount, int Month, int Year);
public sealed record RecurringRequest(Guid AccountId, Guid? CategoryId, TransactionType TransactionType, decimal Amount, string Description, RecurringFrequency Frequency, DateOnly StartDate, DateOnly NextOccurrenceDate, DateOnly? EndDate, bool IsActive);
public sealed record MortgageRequest(string Name, string Lender, string? PropertyAddress, decimal OriginalPrincipal, decimal OutstandingBalance, decimal InterestRate, MortgageRateType RateType, decimal MonthlyPayment, string CurrencyCode, DateOnly StartDate, DateOnly EndDate, int PaymentDay);
public sealed record HouseholdBillRequest(string Name, string Provider, HouseholdBillType BillType, decimal Amount, string CurrencyCode, int BillingDay, DateOnly StartDate, DateOnly? EndDate, bool IsActive);
public sealed record Page<T>(IReadOnlyList<T> Items, int PageNumber, int PageSize, int TotalCount);

public sealed class FinanceService(FinoraDbContext db)
{
    public static Guid UserId(ClaimsPrincipal user) => Guid.Parse(user.FindFirstValue(ClaimTypes.NameIdentifier)!);
    public Task<List<Account>> Accounts(Guid userId) => db.Accounts.AsNoTracking().Where(x => x.UserId == userId).OrderBy(x => x.Name).ToListAsync();
    public async Task<Account> CreateAccount(Guid userId, AccountRequest r) { if (string.IsNullOrWhiteSpace(r.Name) || r.CurrencyCode.Length != 3) throw new ArgumentException("Name and a three-letter currency are required."); var x = new Account { UserId=userId, Name=r.Name.Trim(), AccountType=r.AccountType, CurrencyCode=r.CurrencyCode.ToUpperInvariant(), InitialBalance=r.InitialBalance }; db.Add(x); await db.SaveChangesAsync(); return x; }
    public Task<List<Category>> Categories(Guid userId) => db.Categories.AsNoTracking().Where(x => x.UserId == userId).OrderBy(x => x.Name).ToListAsync();
    public async Task<Category> CreateCategory(Guid userId, CategoryRequest r) { if (string.IsNullOrWhiteSpace(r.Name)) throw new ArgumentException("Name is required."); var x = new Category { UserId=userId, Name=r.Name.Trim(), CategoryType=r.CategoryType, Icon=r.Icon }; db.Add(x); await db.SaveChangesAsync(); return x; }
    public async Task<Page<Transaction>> Transactions(Guid userId, int page, int size, Guid? account, Guid? category, TransactionType? type, DateOnly? start, DateOnly? end, string? search) { var q=db.Transactions.AsNoTracking().Where(x=>x.UserId==userId); if(account.HasValue)q=q.Where(x=>x.AccountId==account); if(category.HasValue)q=q.Where(x=>x.CategoryId==category); if(type.HasValue)q=q.Where(x=>x.TransactionType==type); if(start.HasValue)q=q.Where(x=>x.TransactionDate>=start); if(end.HasValue)q=q.Where(x=>x.TransactionDate<=end); if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.Description.Contains(search)); var count=await q.CountAsync(); var items=await q.OrderByDescending(x=>x.TransactionDate).Skip((page-1)*size).Take(size).ToListAsync(); return new(items,page,size,count); }
    public async Task<Transaction> CreateTransaction(Guid userId, TransactionRequest r) { if(r.Amount<=0)throw new ArgumentException("Amount must be positive."); if(!await db.Accounts.AnyAsync(x=>x.Id==r.AccountId&&x.UserId==userId))throw new KeyNotFoundException("Account not found."); if(r.CategoryId.HasValue&&!await db.Categories.AnyAsync(x=>x.Id==r.CategoryId&&x.UserId==userId))throw new KeyNotFoundException("Category not found."); var x=new Transaction { UserId=userId, AccountId=r.AccountId, CategoryId=r.CategoryId, TransactionType=r.TransactionType, Amount=r.Amount, Description=r.Description.Trim(), TransactionDate=r.TransactionDate, Notes=r.Notes }; db.Add(x); await db.SaveChangesAsync(); return x; }
    public Task<List<Budget>> Budgets(Guid userId) => db.Budgets.AsNoTracking().Where(x=>x.UserId==userId).ToListAsync();
    public async Task<Budget> CreateBudget(Guid userId, BudgetRequest r) { if(r.Amount<=0||r.Month is <1 or >12)throw new ArgumentException("Invalid budget."); if(!await db.Categories.AnyAsync(x=>x.Id==r.CategoryId&&x.UserId==userId))throw new KeyNotFoundException("Category not found."); var x=new Budget { UserId=userId, CategoryId=r.CategoryId, Amount=r.Amount, Month=r.Month, Year=r.Year }; db.Add(x); await db.SaveChangesAsync(); return x; }
    public Task<List<RecurringTransaction>> Recurring(Guid userId) => db.RecurringTransactions.AsNoTracking().Where(x=>x.UserId==userId).ToListAsync();
    public async Task<RecurringTransaction> CreateRecurring(Guid userId, RecurringRequest r) { if(r.Amount<=0)throw new ArgumentException("Amount must be positive."); if(!await db.Accounts.AnyAsync(x=>x.Id==r.AccountId&&x.UserId==userId))throw new KeyNotFoundException("Account not found."); var x=new RecurringTransaction { UserId=userId, AccountId=r.AccountId, CategoryId=r.CategoryId, TransactionType=r.TransactionType, Amount=r.Amount, Description=r.Description, Frequency=r.Frequency, StartDate=r.StartDate, NextOccurrenceDate=r.NextOccurrenceDate, EndDate=r.EndDate, IsActive=r.IsActive }; db.Add(x); await db.SaveChangesAsync(); return x; }
    public Task<List<Mortgage>> Mortgages(Guid userId) => db.Mortgages.AsNoTracking().Where(x => x.UserId == userId).OrderBy(x => x.EndDate).ToListAsync();
    public async Task<Mortgage> CreateMortgage(Guid userId, MortgageRequest r) { if(string.IsNullOrWhiteSpace(r.Name)||string.IsNullOrWhiteSpace(r.Lender))throw new ArgumentException("Name and lender are required."); if(r.OriginalPrincipal<=0||r.OutstandingBalance<0||r.OutstandingBalance>r.OriginalPrincipal)throw new ArgumentException("Outstanding balance must be between zero and the original principal."); if(r.InterestRate<0||r.InterestRate>100||r.MonthlyPayment<=0)throw new ArgumentException("Interest rate and monthly payment are invalid."); if(r.CurrencyCode?.Length!=3)throw new ArgumentException("A three-letter currency is required."); if(r.EndDate<=r.StartDate)throw new ArgumentException("End date must be after the start date."); if(r.PaymentDay is <1 or >31)throw new ArgumentException("Payment day must be between 1 and 31."); var x=new Mortgage { UserId=userId, Name=r.Name.Trim(), Lender=r.Lender.Trim(), PropertyAddress=string.IsNullOrWhiteSpace(r.PropertyAddress)?null:r.PropertyAddress.Trim(), OriginalPrincipal=r.OriginalPrincipal, OutstandingBalance=r.OutstandingBalance, InterestRate=r.InterestRate, RateType=r.RateType, MonthlyPayment=r.MonthlyPayment, CurrencyCode=r.CurrencyCode.ToUpperInvariant(), StartDate=r.StartDate, EndDate=r.EndDate, PaymentDay=r.PaymentDay }; db.Add(x); await db.SaveChangesAsync(); return x; }
    public async Task<Mortgage> UpdateMortgage(Guid userId, Guid id, MortgageRequest r) { if(string.IsNullOrWhiteSpace(r.Name)||string.IsNullOrWhiteSpace(r.Lender))throw new ArgumentException("Name and lender are required."); if(r.OriginalPrincipal<=0||r.OutstandingBalance<0||r.OutstandingBalance>r.OriginalPrincipal)throw new ArgumentException("Outstanding balance must be between zero and the original principal."); if(r.InterestRate<0||r.InterestRate>100||r.MonthlyPayment<=0)throw new ArgumentException("Interest rate and monthly payment are invalid."); if(r.CurrencyCode?.Length!=3)throw new ArgumentException("A three-letter currency is required."); if(r.EndDate<=r.StartDate)throw new ArgumentException("End date must be after the start date."); if(r.PaymentDay is <1 or >31)throw new ArgumentException("Payment day must be between 1 and 31."); var x=await db.Mortgages.FirstOrDefaultAsync(x=>x.Id==id&&x.UserId==userId)??throw new KeyNotFoundException("Mortgage not found."); x.Name=r.Name.Trim(); x.Lender=r.Lender.Trim(); x.PropertyAddress=string.IsNullOrWhiteSpace(r.PropertyAddress)?null:r.PropertyAddress.Trim(); x.OriginalPrincipal=r.OriginalPrincipal; x.OutstandingBalance=r.OutstandingBalance; x.InterestRate=r.InterestRate; x.RateType=r.RateType; x.MonthlyPayment=r.MonthlyPayment; x.CurrencyCode=r.CurrencyCode.ToUpperInvariant(); x.StartDate=r.StartDate; x.EndDate=r.EndDate; x.PaymentDay=r.PaymentDay; x.UpdatedAtUtc=DateTime.UtcNow; await db.SaveChangesAsync(); return x; }
    public Task<List<HouseholdBill>> HouseholdBills(Guid userId) => db.HouseholdBills.AsNoTracking().Where(x=>x.UserId==userId).OrderBy(x=>x.BillingDay).ThenBy(x=>x.Name).ToListAsync();
    public async Task<HouseholdBill> CreateHouseholdBill(Guid userId, HouseholdBillRequest r) { ValidateHouseholdBill(r); var x=new HouseholdBill { UserId=userId, Name=r.Name.Trim(), Provider=r.Provider.Trim(), BillType=r.BillType, Amount=r.Amount, CurrencyCode=r.CurrencyCode.ToUpperInvariant(), BillingDay=r.BillingDay, StartDate=r.StartDate, EndDate=r.EndDate, IsActive=r.IsActive }; db.Add(x); await db.SaveChangesAsync(); return x; }
    public async Task<HouseholdBill> UpdateHouseholdBill(Guid userId,Guid id,HouseholdBillRequest r) { ValidateHouseholdBill(r); var x=await db.HouseholdBills.FirstOrDefaultAsync(x=>x.Id==id&&x.UserId==userId)??throw new KeyNotFoundException("Household bill not found."); x.Name=r.Name.Trim(); x.Provider=r.Provider.Trim(); x.BillType=r.BillType; x.Amount=r.Amount; x.CurrencyCode=r.CurrencyCode.ToUpperInvariant(); x.BillingDay=r.BillingDay; x.StartDate=r.StartDate; x.EndDate=r.EndDate; x.IsActive=r.IsActive; x.UpdatedAtUtc=DateTime.UtcNow; await db.SaveChangesAsync(); return x; }
    private static void ValidateHouseholdBill(HouseholdBillRequest r) { if(string.IsNullOrWhiteSpace(r.Name)||string.IsNullOrWhiteSpace(r.Provider))throw new ArgumentException("Name and provider are required."); if(!Enum.IsDefined(r.BillType))throw new ArgumentException("Bill type is invalid."); if(r.Amount<=0)throw new ArgumentException("Amount must be positive."); if(r.CurrencyCode?.Length!=3)throw new ArgumentException("A three-letter currency is required."); if(r.BillingDay is <1 or >31)throw new ArgumentException("Billing day must be between 1 and 31."); if(r.EndDate.HasValue&&r.EndDate.Value<r.StartDate)throw new ArgumentException("End date cannot be before the start date."); }
    public async Task<object> Dashboard(Guid userId,int month,int year) { if(month is <1 or >12)throw new ArgumentException("Invalid month."); var tx=await db.Transactions.AsNoTracking().Where(x=>x.UserId==userId&&x.TransactionDate.Month==month&&x.TransactionDate.Year==year).ToListAsync(); var income=tx.Where(x=>x.TransactionType==TransactionType.Income).Sum(x=>x.Amount); var transactionExpenses=tx.Where(x=>x.TransactionType==TransactionType.Expense).Sum(x=>x.Amount); var monthStart=new DateOnly(year,month,1); var monthEnd=monthStart.AddMonths(1).AddDays(-1); var mortgageExpenses=await db.Mortgages.AsNoTracking().Where(x=>x.UserId==userId&&x.StartDate<=monthEnd&&x.EndDate>=monthStart&&x.OutstandingBalance>0).SumAsync(x=>(decimal?)x.MonthlyPayment)??0; var householdBillExpenses=await db.HouseholdBills.AsNoTracking().Where(x=>x.UserId==userId&&x.IsActive&&x.StartDate<=monthEnd&&(!x.EndDate.HasValue||x.EndDate>=monthStart)).SumAsync(x=>(decimal?)x.Amount)??0; var expenses=transactionExpenses+mortgageExpenses+householdBillExpenses; var budgets=await db.Budgets.Where(x=>x.UserId==userId&&x.Month==month&&x.Year==year).SumAsync(x=>(decimal?)x.Amount)??0; var initial=await db.Accounts.Where(x=>x.UserId==userId&&!x.IsArchived).SumAsync(x=>(decimal?)x.InitialBalance)??0; var categoryNames=await db.Categories.Where(x=>x.UserId==userId).ToDictionaryAsync(x=>x.Id,x=>x.Name); var spending=tx.Where(x=>x.TransactionType==TransactionType.Expense).GroupBy(x=>x.CategoryId).Select(g=>new { category=g.Key.HasValue&&categoryNames.TryGetValue(g.Key.Value,out var n)?n:"Uncategorized", amount=g.Sum(x=>x.Amount)}).ToList(); if(mortgageExpenses>0)spending.Add(new {category="Mortgage",amount=mortgageExpenses}); if(householdBillExpenses>0)spending.Add(new {category="Household bills",amount=householdBillExpenses}); return new { totalBalance=initial+income-expenses, monthlyIncome=income, monthlyExpenses=expenses, mortgageExpenses, householdBillExpenses, remainingBudget=budgets-expenses, recentTransactions=tx.OrderByDescending(x=>x.TransactionDate).Take(5), spendingByCategory=spending, cashFlow=new[]{new { month, year, income, expenses }} }; }
}
